export const services = [
  { id: 1, name: "Bathroom Cleaning", price: 499 },
  { id: 2, name: "Occupied Flat Deep Cleaning (1BHK)", price: 3999 },
  { id: 3, name: "Occupied Flat Deep Cleaning (2BHK)", price: 4999 },
  { id: 4, name: "Occupied Flat Deep Cleaning (3BHK)", price: 5999 },
  { id: 5, name: "Occupied Flat Deep Cleaning (4BHK)", price: 6999 },
  { id: 6, name: "Vacant Flat Deep Cleaning (1BHK)", price: 3499 },
  { id: 7, name: "Vacant Flat Deep Cleaning (2BHK)", price: 4499 },
  { id: 8, name: "Vacant Flat Deep Cleaning (3BHK)", price: 5499 },
  { id: 9, name: "Vacant Flat Deep Cleaning (4BHK)", price: 7999 },
  { id: 10, name: "Water Tank Cleaning", price: 699 },
  { id: 11, name: "Chair Cleaning", price: 99 },
  { id: 12, name: "Single Room Cleaning", price: 999 },
  { id: 13, name: "2 Room Cleaning", price: 2999 },
  { id: 14, name: "3 Room Cleaning", price: 3999 },
  { id: 15, name: "4 Room Cleaning", price: 4999 },
  { id: 16, name: "Kitchen (Occupied)", price: 5299 },
  { id: 17, name: "Vacant Kitchen", price: 899 },
  { id: 18, name: "AC Service", price: 699 },
  {id:19,name:"Building" ,price:0},
  {id:20,name:"Villa" ,price:0},
];
